### ISSUE TITLE
graph URNs

### ISSUE THREAD

**Issue by fils** [gleanerio/nabu#1]
There is an issue on the connection between Gleaner operation and Nabu.

The selection of namespaces for the "graph first approach" in Gleaner impacts the config file for Nabu with respect to where it looks for loading the Gleaner output.  It would be better if the selection between raw summoned files and processes miller files was not a "convention" based on the source type (sitemap vs sitegraph).  

I had a note this could impact queries too, however, that doesn't seem likely as the graph quad holds prov relations/references and is never part of the discovery aspect of the query.

**Comment by valentinedwv** [comment]
[decision](https://github.com/gleanerio/nabu/blob/dev/decisions/0001-URN-decision.md)
